#! /usr/bin/env ruby

require 'pg'

def list_espenses
  dbconnection = PG.connect(dbname:"expenses")

  results = dbconnection.exec("SELECT * FROM expenses;")
  results.each do |tuple|
    columns = [ tuple["id"].rjust(3),
                tuple["created_on"].rjust(10),
                tuple["amount"].rjust(12),
                tuple["memo"] ]

    puts columns.join(" | ")
  end
end

def display_help 
  puts <<~HELP
        An expense recording system

        Commands:

        add AMOUNT MEMO - record a new expense
        clear - delete all expenses
        list - list all expenses
        delete NUMBER - remove expense with id NUMBER
        search QUERY - list expenses with a matching memo field"
    HELP
end

command = ARGV.first
if command == "list"
  list_espenses
else
  display_help
end